/**
 * 새 codex 팀원의 CODEX_HOME/config.toml 을 만든다.
 *
 * ★제품 결정(2026-08-18): 호스트 설정을 상속한다.★
 * 이전에는 최소 config 만 렌더하고 호스트 설정 복사를 금지했다. 그 결과 새로 영입한 팀원은
 * 플러그인·MCP 없이 떠서, 파일이 먼저 있어 시딩이 건너뛴 팀원(dex)보다 ★기능이 좁았다.★
 * 팀원마다 할 수 있는 일이 다르면 같은 과제를 맡길 수 없다.
 *
 * ★상속하는 것은 능력, 걷어내는 것은 정책·신뢰·정체성.★
 *   물려준다: 모델 · 플러그인 · MCP 서버 정의 · 마켓플레이스 · 기능 토글
 *
 *   ① 정책 — `sandbox_mode` · `approval_policy` · `[sandbox_workspace_write]`
 *      실행 모드는 `appServerRunner` 가 codex 프로토콜로 명시하는 ★한 곳★ 에서만 정해진다.
 *      설정 파일에도 적으면 두 곳이 갈리는데 어느 쪽이 이기는지는 아직 측정되지 않았다
 *      (docs/RUNTIME_ACCEPTANCE.md 판정 규칙 0). 한 곳으로 두면 그 질문 자체가 생기지 않는다.
 *
 *   ② 신뢰 — `[projects."<경로>"]` 전부
 *      ★trust 는 능력이 아니라 권한이다.★ 호스트 설정에는 홈·다른 팀원 폴더·스크래치까지
 *      신뢰 표시가 쌓여 있다(이 기계 실측 12개). 그대로 물려주면 새 팀원마다 그 권한을 들고 뜬다.
 *      대신 ★그 팀원의 작업 폴더 하나만★ 새로 써 넣는다.
 *
 *   ③ 정체성 — 값이 ★호스트 CODEX_HOME 을 가리키는 줄★ (예: `CODEX_HOME` ·
 *      `NODE_REPL_TRUSTED_CODE_PATHS`). `codexHome` 은 팀원별 정체성 격리 장치인데,
 *      그 안에 호스트 경로를 심어 배포하면 새 팀원의 MCP 가 호스트 설정·인증을 본다.
 *
 * ★이어붙이지 않고 지운다.★ TOML 은 같은 키가 두 번 나오면 파싱 자체가 실패한다 —
 * 덮어쓰기를 append 로 구현하면 설정 파일이 통째로 깨진다.
 */

/** ① 정책 — 걷어내는 최상위 키. */
export const POLICY_KEYS = ["sandbox_mode", "approval_policy"] as const;
/** ① 정책 — 걷어내는 테이블. */
export const POLICY_TABLES = ["sandbox_workspace_write"] as const;
/** ② 신뢰 — 이 접두사로 시작하는 테이블은 전부 걷어낸다. */
export const TRUST_TABLE_PREFIX = "projects.";

/** 첫 테이블 헤더([...]) 앞까지가 최상위 스코프다. */
function topLevelEnd(lines: string[]): number {
  const i = lines.findIndex((l) => /^\s*\[/.test(l));
  return i === -1 ? lines.length : i;
}

/** 최상위 key 를 지운다. 테이블 안의 같은 이름은 건드리지 않는다. */
export function removeTopLevelKey(toml: string, key: string): string {
  const lines = toml.split("\n");
  const end = topLevelEnd(lines);
  const re = new RegExp(`^\\s*${key}\\s*=`);
  return lines.filter((l, i) => !(i < end && re.test(l))).join("\n");
}

/** [table] 을 통째로 지운다(다음 테이블 헤더 직전까지). */
export function removeTable(toml: string, table: string): string {
  const lines = toml.split("\n");
  const start = lines.findIndex((l) => l.trim() === `[${table}]`);
  if (start === -1) return toml;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^\s*\[/.test(lines[i]!)) { end = i; break; }
  }
  lines.splice(start, end - start);
  return lines.join("\n");
}

/** 접두사로 시작하는 테이블을 전부 지운다(`[projects."..."]` 처럼 이름이 가변인 경우). */
export function removeTablesWithPrefix(toml: string, prefix: string): string {
  const lines = toml.split("\n");
  const out: string[] = [];
  let skipping = false;
  for (const l of lines) {
    if (/^\s*\[/.test(l)) skipping = l.trim().startsWith(`[${prefix}`);
    if (!skipping) out.push(l);
  }
  return out.join("\n");
}

/**
 * 값이 특정 경로를 가리키는 줄을 지운다(정체성 누출 차단).
 * 키 이름이 아니라 ★값★ 으로 판정한다 — CODEX_HOME 만 막으면 같은 값을 다른 이름으로 실은 줄이 남는다.
 */
export function removeLinesReferencing(toml: string, needle: string): string {
  if (needle === "") return toml;
  return toml
    .split("\n")
    .filter((l) => !(/^\s*[A-Za-z_][A-Za-z0-9_]*\s*=/.test(l) && l.includes(needle)))
    .join("\n");
}

/** 호스트 설정이 없을 때. 상속할 것이 없어도 팀원은 떠야 한다. */
export function renderFallbackCodexConfig(): string {
  return [
    "# Generated by b3rys team-collab (host ~/.codex/config.toml 이 없어 빈 설정으로 시드).",
    "# 실행 모드는 이 파일이 아니라 appServerRunner 가 codex 프로토콜로 명시한다.",
    "",
  ].join("\n");
}

/** TOML 문자열 리터럴(경로에 공백·따옴표가 있어도 안전). */
export function tomlString(v: string): string {
  return JSON.stringify(v);
}

/**
 * 시드할 config 본문. 능력은 물려주고 정책·신뢰·정체성은 걷어낸다.
 * `workdir` 는 그 팀원의 작업 폴더, `hostCodexHome` 은 호스트 CODEX_HOME 경로다.
 */
export function renderSeededCodexConfig(
  hostConfig: string | null,
  opts: { workdir: string; hostCodexHome: string },
): string {
  if (hostConfig === null || hostConfig.trim() === "") return renderFallbackCodexConfig();
  let out = hostConfig;
  for (const k of POLICY_KEYS) out = removeTopLevelKey(out, k);   // ① 정책
  for (const t of POLICY_TABLES) out = removeTable(out, t);
  out = removeTablesWithPrefix(out, TRUST_TABLE_PREFIX);           // ② 신뢰
  out = removeLinesReferencing(out, opts.hostCodexHome);           // ③ 정체성
  // 그 팀원의 작업 폴더만 새로 신뢰한다.
  const tail = out.endsWith("\n") ? "" : "\n";
  return `${out}${tail}\n[projects.${tomlString(opts.workdir)}]\ntrust_level = "trusted"\n`;
}
