// codex 런처(M4) 순수 렌더러 테스트 — fs/launchctl 부작용 없음. 보안핀: 토큰이 plist/wrapper 평문에 안 들어감.
import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Database } from "bun:sqlite";
import { codexBridgeLaunchdLabel, codexBridgePaths, renderLaunchWrapper, renderBridgePlist, ensureCodexHome, renderLockedDownCodexConfig, persistOwnerChatIdIfEmpty } from "./launcher";

describe("persistOwnerChatIdIfEmpty — 자동저장(자연 도출값 persist, 사용자 입력 보호)", () => {
  test("기존 owner_chat_id 는 절대 덮지 않는다(사용자 입력 우선)", () => {
    const db = new Database(":memory:");
    db.query("CREATE TABLE setting (key TEXT PRIMARY KEY, value TEXT, updated_at TEXT)").run();
    db.query("INSERT INTO setting (key, value) VALUES ('owner_chat_id', '99999')").run();
    expect(persistOwnerChatIdIfEmpty(db)).toBe("99999");
    expect((db.query("SELECT value FROM setting WHERE key='owner_chat_id'").get() as { value: string }).value).toBe("99999");
    db.close();
  });

  test("setting 테이블 없어도 던지지 않고 null(best-effort)", () => {
    const db = new Database(":memory:");
    expect(persistOwnerChatIdIfEmpty(db)).toBeNull();
    db.close();
  });
});

describe("codex launcher (M4) — 순수 렌더러", () => {
  test("라벨 = prefix.codex-bridge-<id>", () => {
    expect(codexBridgeLaunchdLabel("cody")).toMatch(/\.codex-bridge-cody$/);
  });

  test("paths: plist/wrapper/token/workdir/log 구성", () => {
    const p = codexBridgePaths("cody");
    expect(p.plist).toMatch(/LaunchAgents\/.*codex-bridge-cody\.plist$/);
    expect(p.wrapper).toMatch(/codex-bridge\/cody-launch\.sh$/);
    expect(p.tokenFile).toMatch(/var\/secrets\/cody\.bot-token$/);
    expect(p.workdir).toMatch(/\/cody$/);
  });

  test("plist: Label + wrapper 참조 + KeepAlive, 토큰 없음", () => {
    const p = codexBridgePaths("cody");
    const xml = renderBridgePlist(p);
    expect(xml).toContain(p.label);
    expect(xml).toContain(p.wrapper);
    expect(xml).toContain("KeepAlive");
    expect(xml).not.toContain("bot-token\n"); // 토큰값 자체는 plist에 없음(wrapper가 파일서 읽음)
    expect(xml).not.toMatch(/[0-9]{8,}:[A-Za-z0-9_-]{30,}/); // 텔레그램 토큰 형식 없음
  });

  test("wrapper: 토큰 파일→env(평문 노출 없음) + bridge.ts exec", () => {
    const p = codexBridgePaths("cody");
    const sh = renderLaunchWrapper(p);
    expect(sh).toContain(`TOKEN_FILE="${p.tokenFile}"`); // 토큰 경로
    expect(sh).toContain(`export CODEX_BOT_TOKEN="$(cat "$TOKEN_FILE")"`); // 파일서 env로(변수 경유)
    expect(sh).toContain(`export CODEX_WORKDIR="${p.workdir}"`);
    expect(sh).toContain(`export CODEX_ALLOW_FROM="${p.allowFrom}"`); // ★발신자 게이트 시드 배선(P0) — 이게 있어야 게이트가 라이브에서 켜짐
    expect(sh).toContain("export B3OS_REPO_ROOT=");
    expect(sh).toContain("export TEAM_BASE_URL=");
    expect(sh).toContain("export CODEX_SCHEDULE_TOOL_ENABLED=");
    expect(sh).toContain("bridge.ts");
    expect(sh).not.toMatch(/[0-9]{8,}:[A-Za-z0-9_-]{30,}/); // 평문 토큰 없음
    // PATH 에 bun 설치경로가 있어야 launchd 최소 PATH 에서도 exec bun 이 해석됨(없으면 respawn-loop). claude launcher 와 동일 세트.
    expect(sh).toContain(`export PATH="${process.env.HOME ?? ""}/.bun/bin:`); // ~/.bun/bin 선두(공식 인스톨러 경로)
    expect(sh).toContain("/usr/local/bin"); // Intel homebrew
  });

  test("ensureCodexHome: CODEX_HOME 디렉토리 보장(없으면 codex exec 즉사→Codi 인시던트 재발)", () => {
    const tmp = join(tmpdir(), `codex-home-test-${process.pid}-${Math.random().toString(36).slice(2)}`);
    const p = { ...codexBridgePaths("cody"), codexHome: tmp };
    expect(existsSync(tmp)).toBe(false);
    ensureCodexHome(p); // 디렉토리 생성 + (호스트 ~/.codex 있으면) auth seed
    expect(existsSync(tmp)).toBe(true);
    rmSync(tmp, { recursive: true, force: true });
  });

  test("locked-down config: host trust/MCP/plugins 없이 read-only + workspace-only roots를 렌더", () => {
    const cfg = renderLockedDownCodexConfig({ workdir: "/tmp/cody workspace" });
    expect(cfg).toContain('sandbox_mode = "read-only"');
    expect(cfg).toContain('approval_policy = "on-request"');
    expect(cfg).toContain("network_access = false");
    expect(cfg).toContain('writable_roots = ["/tmp/cody workspace"]');
    expect(cfg).not.toContain("mcp_servers");
    expect(cfg).not.toContain("plugins");
    expect(cfg).not.toContain("trust_level");
  });

  test("ensureCodexHome: host config.toml을 복사하지 않고 locked-down config를 생성", () => {
    const tmp = join(tmpdir(), `codex-home-test-${process.pid}-${Math.random().toString(36).slice(2)}`);
    const p = { ...codexBridgePaths("cody"), codexHome: tmp, workdir: "/tmp/cody" };
    ensureCodexHome(p);
    const cfgPath = join(tmp, "config.toml");
    expect(existsSync(cfgPath)).toBe(true);
    const cfg = readFileSync(cfgPath, "utf-8");
    expect(cfg).toContain("# Generated by b3rys team-collab");
    expect(cfg).toContain('writable_roots = ["/tmp/cody"]');
    expect(cfg).not.toContain("mcp_servers");
    expect(cfg).not.toContain("plugins");
    rmSync(tmp, { recursive: true, force: true });
  });

  test("ensureCodexHome: 기존 per-agent config는 덮어쓰지 않음", () => {
    const tmp = join(tmpdir(), `codex-home-test-${process.pid}-${Math.random().toString(36).slice(2)}`);
    const p = { ...codexBridgePaths("cody"), codexHome: tmp, workdir: "/tmp/cody" };
    ensureCodexHome(p);
    const cfgPath = join(tmp, "config.toml");
    writeFileSync(cfgPath, "# custom per-agent config\n", "utf-8");
    ensureCodexHome(p);
    expect(readFileSync(cfgPath, "utf-8")).toBe("# custom per-agent config\n");
    rmSync(tmp, { recursive: true, force: true });
  });
});
