#!/usr/bin/env node
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const tmp = mkdtempSync(join(tmpdir(), "b3os-report-test-"));
try {
  const md = join(tmp, "input.md");
  const out = join(tmp, "output.html");
  writeFileSync(md, `# 라이트 보고서\n\n<div class="outer">\n  <div class="hint">안내</div>\n  <svg viewBox="0 0 100 40" role="img" aria-label="테스트 차트">\n    <rect x="1" y="1" width="98" height="38" fill="#ffffff"/>\n    <text x="50" y="24" text-anchor="middle" fill="#172033">정상 SVG</text>\n  </svg>\n</div>\n\n<figure><figcaption>한눈에 보기</figcaption><div class="mobile-infographic"><div class="mi-card mi-blue"><h4>모바일</h4><p>세로 카드</p></div></div><svg class="desktop-infographic" viewBox="0 0 100 40"><text x="10" y="20">데스크톱</text></svg></figure>\n\n본문입니다.\n`, "utf8");
  execFileSync(process.execPath, [join(here, "render.mjs"), md, out, "--title", "테스트"], { stdio: "pipe" });
  const html = readFileSync(out, "utf8");
  assert.match(html, /<html lang="ko" data-theme="dark">/);
  assert.match(html, /color-scheme:dark/);
  assert.match(html, /--bg:#0a0f0d/);
  assert.match(html, /--card:#111a15/);
  assert.match(html, /--glow:rgba\(52,211,153,\.16\)/);
  assert.match(html, /--grid:rgba\(52,211,153,\.040\)/);
  assert.match(html, /--blue:#9fc7ac/);
  assert.match(html, /linear-gradient\(90deg,var\(--grid\) 1px,transparent 1px\)/);
  assert.match(html, /linear-gradient\(var\(--grid\) 1px,transparent 1px\)/);
  assert.match(html, /h3\{[^}]*color:var\(--green\)/);
  assert.match(html, /\.report-tabs\{[^}]*backdrop-filter:blur\(14px\)/);
  assert.match(html, /\.report-tab\{[^}]*min-height:34px/);
  assert.match(html, /\.report-tab\.is-active[^}]*box-shadow:none/);
  assert.match(html, /body>\.report-toolbar\{max-width:960px/);
  assert.match(html, /body>\.wrap\{max-width:960px/);
  assert.match(html, /\.tab-shell\{position:sticky;top:57px[^}]*display:flex/);
  assert.match(html, /\.tab-shell\{[^}]*overflow-x:auto/);
  assert.match(html, /\.tab-shell\{[^}]*scrollbar-width:none/);
  assert.match(html, /\.tab-nav\{[^}]*flex-wrap:nowrap/);
  assert.match(html, /\.tab-btn,\.pager-btn\{[^}]*min-height:29px/);
  assert.match(html, /\.tab-btn,\.pager-btn\{[^}]*white-space:nowrap/);
  assert.match(html, /\.tab-panel\{display:none/);
  assert.match(html, /\.tab-panel\.active\{display:block\}/);
  assert.match(html, /\[data-theme="light"\]/);
  assert.match(html, /--bg:#f6f8f5/);
  assert.match(html, /--grid:rgba\(22,136,77,\.052\)/);
  assert.match(html, /class="theme-switch"/);
  assert.match(html, /localStorage\.getItem\('b3os-report-theme'\)/);
  assert.match(html, /\.wrap>h1:first-child::before/);
  assert.match(html, /\.mobile-infographic\{display:none\}/);
  assert.match(html, /\.mi-card p\{[^}]*color:var\(--ink\)\}/);
  assert.doesNotMatch(html, /\[data-theme="light"\] svg text\{fill:var\(--mut\)\}/);
  assert.match(html, /\[data-theme="light"\] svg text\[fill="#e6edf3"\][^}]*\{fill:var\(--ink\)\}/);
  assert.match(html, /\.desktop-infographic\{display:block\}/);
  assert.match(html, /figure img,\.report-image\{display:block;width:100%;height:auto;border:1px solid var\(--line\)/);
  assert.match(html, /\.image-grid\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(html, /\.lede\{font-size:18px/);
  assert.match(html, /\.stat-grid\{display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
  assert.match(html, /\.stat-card b\{display:block;color:var\(--green\);font-size:24px/);
  assert.match(html, /\.diagram-flow\{--diagram-green:#10a36f;--diagram-green-soft:#36c18a;--diagram-gold:#d49421/);
  assert.match(html, /\[data-theme="light"\] \.diagram-flow\{--diagram-green:#0f9f6e;--diagram-green-soft:#2fbf87/);
  assert.match(html, /\.diagram-flow \.diagram-node-primary\{fill:var\(--diagram-neutral\);stroke:color-mix\(in srgb,var\(--diagram-green\) 72%,var\(--diagram-stroke\)\);stroke-width:1\.8\}/);
  assert.doesNotMatch(html, /diagram-accent-bar/);
  assert.match(html, /\.diagram-flow \.diagram-text\{fill:var\(--ink\);font:650 13px\/1\.2 var\(--sans\)/);
  assert.match(html, /\.diagram-flow \.diagram-line-warm\{stroke:var\(--diagram-gold\)/);
  assert.match(html, /\.desktop-infographic\{display:none!important\}/);
  assert.match(html, /<div class="outer">[\s\S]*<div class="hint">안내<\/div>[\s\S]*<svg/);
  assert.match(html, /<figure><figcaption>한눈에 보기<\/figcaption><div class="mobile-infographic">[\s\S]*<svg class="desktop-infographic"/);
  assert.match(html, /<rect x="1"/);
  assert.match(html, /<text x="50"/);
  const refs = readFileSync(new URL('../references/ui-components.md', import.meta.url), 'utf8');
  assert.match(refs, /Vertical flowchart/);
  assert.match(refs, /Tree \/ hierarchy/);
  assert.match(refs, /Swimlane/);
  assert.match(refs, /Funnel \/ narrowing/);
  assert.match(refs, /Radial \/ hub-and-spoke/);
  assert.match(refs, /Sankey-lite \/ weighted flow/);
  assert.match(refs, /Timeline \/ lineage/);
  assert.match(refs, /milestone을 위\/아래로 stagger 배치/);
  assert.match(refs, /hard-coded white\/blue\/violet fill/);
  assert.match(refs, /Matrix \/ quadrant/);
  assert.doesNotMatch(html, /&lt;(svg|rect|text|div)/);
  assert.match(html, /<p>본문입니다\.<\/p>/);
  console.log("PASS b3os-report dark/light theme + nested raw block passthrough");
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
